name: Dolt Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dolt
        run: |
          sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'

      - name: Clone juicebox repository
        run: dolt clone jigglyjams/juicebox

      - name: Change directory to juicebox
        run: cd juicebox

      - name: Run doltdump and save output
        run: dolt doltdump > ../dolt_output.txt
                
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload output to IPFS
        id: ipfsPin
        run: |
          npm install axios form-data
          node ipfsPin.js
          env:
            INFURA_IPFS_ID: ${{ secrets.INFURA_IPFS_ID }}
            INFURA_IPFS_SECRET: ${{ secrets.INFURA_IPFS_SECRET }}
            
      - name: Display IPFS CID
        run: |
          echo "IPFS CID: ${{ steps.ipfsPin.outputs.ipfs-cid }}"
